### PR TITLE
Fix layout animations interrupted by rerenders

### LINKED ISSUE #1085: [BUG] State updates still interrupting layout animations
**Describe the bug**

This was reported in #732 and fixed in #1018 (v3.10.1), but it seems there still is an issue.

**CodeSandbox reproduction of the bug**

https://codesandbox.io/s/9eh9p?file=/src/Modal.tsx

**Steps to reproduce**

1. Click on a blue square
2. ☑️ Open animation no longer interrupted by state updates
3. Close modal
4. ❌ Close animation is interrupted by state update, comment icon seems to start new animation with default transition, border radius does not return to 10:

https://user-images.githubusercontent.com/159500/113399830-297ce200-93a1-11eb-91c4-82be7f784584.mov

**Expected behavior**

Comment out the `useEffect` in `Modal.tsx` to see the expected behaviour:

https://user-images.githubusercontent.com/159500/113399880-3b5e8500-93a1-11eb-82f3-a0cd622af027.mov

### PR DESCRIPTION
**Pull request by rijk**
Supersedes #1181.

**Problem**
State updates that happen during a layout transition, trigger a new call to `animate()`. What then happens is this:

1. For the intial layout animation, the axis animations are added to `Promise.all()` and all is well
2. A state change happens, triggering a new call to `animate()`
3. No (new) animations; `Promise.all()` is called with no animations and resolves immediately
4. `visualElement.notifyLayoutAnimationComplete()` is called — before the promises from step 1 have resolved.

As a result the exiting element disappears mid transition, and a new transition is started for the following element. This can be seen in the Sandbox from the linked issue. 

**Solution**
This change prevents no-op rerenders (e.g. internal state changes that don’t result in a layout animation) from calling `Promise.all()` with `[undefined, undefined]` resulting in a preliminary call to `onComplete()` and `visualElement.notifyLayoutAnimationComplete()`.

Fixes #1085.

### CODE REVIEW

**Comment by rijk** [comment]
Ok, it's failing the `drag-svg` and `layout-shared-lightbox-crossfade-repeated` e2e tests at the moment. Need to do some more research (or feel free to improve yourself) and will also add a test for this case.

**Comment by rijk** [comment]
To be honest, I don't think the original one should be passing either:

https://user-images.githubusercontent.com/159500/121568482-09604380-ca20-11eb-8f63-f2eaf8d8b528.mp4

When I run the test (http://localhost:9990/?test=layout-shared-lightbox-crossfade&partial-ease=true) manually, I get the lightbox when clicking the green or blue box, but the red one is giving me this weird intermittent state as well:

image

This even happens on `main`, so might be an issue that has gone unnoticed.

**Comment by rijk** [comment]
Ok, I think I got it now. Tests are passing.

**Review by mattgperry — APPROVED** [review]

**Comment by mattgperry** [comment]
Yeah this is only possible with Cypress, though I'm not 100% how you'd test this. Some of the ways I've been doing it is writing demos that use a `transition` of `ease: () => 0.5` and ensuring at least the mid-point of the animation is correct but I'm not sure if that would help in this instance. The change looks good to me though.

File: src/motion/features/layout/Animate.tsx [hunk 1]
```diff
@@ -281,19 +281,21 @@ class Animate extends React.Component<AnimateProps> {
...
-            this.isAnimatingTree = false
-            onComplete && onComplete()
-            visualElement.notifyLayoutAnimationComplete()
-        })
+        if (animations.filter(Boolean).length) {
+            // Force a render to ensure there's no flash of uncorrected bounding box.
+            visualElement.syncRender()
+
+            return Promise.all(animations).then(() => {
+                this.isAnimatingTree = false
```
Comment (mattgperry) [inline src/motion/features/layout/Animate.tsx:294]: If `animate` has been called and `this.isAnimatingTree` set to `true`, when will it get set to `false` if no animations are created?

File: src/motion/features/layout/Animate.tsx [hunk 2]
```diff
@@ -281,19 +281,21 @@ class Animate extends React.Component<AnimateProps> {
...
+                onComplete && onComplete()
+                visualElement.notifyLayoutAnimationComplete()
+            })
+        }
```
Comment (mattgperry) [inline src/motion/features/layout/Animate.tsx:298]: Perhaps

```
 else if (shouldStackAnimate) { this.isAnimatingTree = false }
```

File: src/motion/features/layout/Animate.tsx (hunk 1 above)
Comment (rijk) [reply src/motion/features/layout/Animate.tsx:294]: I tried searching the codebase but I don't see it being used anywhere:

image

**Comment by rijk** [comment]
Hi @mattgperry , could you merge this into `fix/jump` and publish a beta update? Cheers

File: src/motion/features/layout/Animate.tsx (hunk 1 above)
Comment (mattgperry) [reply src/motion/features/layout/Animate.tsx:294]: `shouldStackAnimate` is a Framer-internal thing so it isn't provided by anything in Motion

**Comment by mattgperry** [comment]
Yeah can you add this https://github.com/framer/motion/pull/1183#discussion_r649772071

**Review by mattgperry — APPROVED** [review]
