### PR TITLE
Ensure AnimatePresence executes exiting animations in sequence

### LINKED ISSUE #2462: [BUG] `AnimatePresence` does not execute exiting animations in sequence during fast renders
**1. Read the [FAQs](#faqs) 👇**
✅

**2. Describe the bug**
Items with an exit animation within the `<AnimatePresence />` component do not reliably exit in sequence during fast renders.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/p/devbox/dreamy-liskov-q35pmx

**4. Steps to reproduce**
1. Click on the 'Add' button a few times in quick succession.
2. Notice that the list items that appear below the button exit in a non-sequential order.

**5. Expected behavior**
The list items should exit in sequential order even during fast renders.

**6. Video or screenshots**

https://github.com/framer/motion/assets/62209188/d73c8cdc-8cdd-4037-adda-d9cd901c613c

Notice that 'hey 6' jumped above 'hey 5' at the 0:04 second mark, while 'hey 7' disappeared before it's supposed to.

### PR DESCRIPTION
**Pull request by regexyl**
This PR fixes #2462. 

It also fixes 3 tests (i.e. "Only renders one child at a time if mode === 'wait'", "Fast animations with wait render the child content correctly", "Fast animations with wait render the child content correctly (strict mode disabled)") where not enough leeway is given for exiting elements to completely exit from the DOM.

# Before

https://github.com/framer/motion/assets/62209188/d73c8cdc-8cdd-4037-adda-d9cd901c613c

# Now

https://github.com/framer/motion/assets/62209188/da6e0868-f36e-4d95-a13f-4486389d8b7f

### CODE REVIEW

File: packages/framer-motion/src/components/AnimatePresence/index.tsx [hunk 1]
```diff
@@ -96,17 +96,14 @@ export const AnimatePresence: React.FunctionComponent<
...
+    filteredChildren.current = onlyElements(children)
+    let childrenToRender = filteredChildren.current
 
     const exitingChildren = useRef(
         new Map<ComponentKey, ReactElement<any> | undefined>()
     ).current
 
-    // Keep a living record of the children we're actually rendering so we
-    // can diff to figure out which are entering and exiting
-    const presentChildren = useRef(childrenToRender)
```
Comment (regexyl) [inline packages/framer-motion/src/components/AnimatePresence/index.tsx:108]: Removed `presentChildren` for clarity - `filteredChildren`, `exitingChildren` and `allChildren` are enough to maintain the status quo

**Comment by regexyl** [comment]
@mattgperry I'm not sure why the test under framer-motion-3d is failing - do you have a clue?

**Comment by JaeSeoKim** [comment]
In the past, PRs related to this issue have been closed due to personal circumstances, so it's good to know!

- #1569

**Comment by regexyl** [comment]
Thanks @JaeSeoKim! Just had a quick look-through, and it seems like there are two main problems the PR was trying to solve - (1) bringing `useRef` to `exitingChildren` (also later separately solved through #2113), and (2) the algorithm that decides how exiting, current and entering elements mesh together.

This PR tries to solve a different problem where a quick waterfall of existing elements do not exit in sequence (i.e. elements exit in quick succession, but in different times), instead of how the exiting/current/entering elements should be rendered - though it seems like a pretty interesting problem to solve 🦄

**Comment by mattgperry** [comment]
Thanks for the excellent PR and apologises it's taken a while to get to. I'll merge and publish today.

**Comment by mattgperry** [comment]
Ah apologises. I had to revert this PR because of these lines:

```javascript
    const filteredChildren = useRef(onlyElements(children))
    filteredChildren.current = onlyElements(children)
```

The intention here is to update `filteredChildren` every render. But `filteredChildren` is essentially a mutable here and React renders are theoretically pure. 

Therefore, it's only safe to assign a `ref` during render on the initial render:

```javascript
    const filteredChildren = useRef(null)
    if (!filteredChildren.current)
      filteredChildren.current = onlyElements(children)
```

(Which obviously isn't the intent of this line)

Otherwise what we have is a situation where React could render something with a `children` list that isn't committed, and an Effect or `onExit` being run on a `children` list that isn't the one we think it is.

**Comment by mattgperry** [comment]
Another issue - or maybe it's been fixed in the meantime? - is I ported the tests in this PR to `main` https://github.com/framer/motion/commit/8ee362878b1e18f4ea30df6239f33ce8806361ba and they pass already so I don't know if they capture the behaviour in the linked issue
